# -*- encoding: utf-8 -*-

{
    'name': 'Connect',
    'version': '1.16.0',
    'author': 'Oduist',
    'maintainer': 'Oduist',
    'price': 0,
    'currency': 'EUR',
    'support': 'support@oduist.com',
    'license': 'OPL-1',
    'category': 'Phone',
    'summary': 'Twilio and Odoo integration application',
    'description': '',
    'depends': ['mail', 'contacts', 'sms'],
    'external_dependencies': {
        'python': ['twilio', 'openai', 'numpy', 'samplerate'],
    },
    'data': [
        'data/res_users.xml',
        'data/data.xml',
        'data/functions.xml',
        'data/ir_cron.xml',
        'data/twiml.xml',
        'data/res_partner.xml',
        'data/whatsapp_templates.xml',
        # Security
        'security/groups.xml',
        'security/admin.xml',
        'security/webhook.xml',
        'security/user.xml',
        'security/user_record_rules.xml',
        'security/admin_record_rules.xml',
        # Data (post-security)
        'data/schedule_data.xml',
        'data/audio.xml',
        # Views
        'views/menu.xml',
        'views/settings.xml',
        'views/domain.xml',
        'views/user.xml',
        'views/twiml.xml',
        'views/debug.xml',
        'views/exten.xml',
        'views/call.xml',
        'views/call_analytics.xml',
        'views/park_slot.xml',
        'views/schedule.xml',
        'views/callflow.xml',
        'views/channel.xml',
        'views/outgoing_callerid.xml',
        'views/recording.xml',
        'views/audio.xml',
        'views/number.xml',
        'views/favorite.xml',
        'views/res_partner.xml',
        'views/message.xml',
        'views/message_configuration.xml',
        'views/message_content_template.xml',
        'views/whatsapp_sender.xml',
        'views/versions.xml',
        'views/documentation.xml',
        # Wizard
        'wizard/transfer.xml',
        'wizard/sms_composer_views.xml',
        'wizard/whatsapp_composer_views.xml',
        'wizard/originate_to_wizard_views.xml',
        'wizard/conversation_wizard_views.xml',
        # Conversation views (after wizard, references wizard action)
        'views/conversation.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'images': ['static/description/logo.png'],
    'assets': {
        'web.assets_backend': [
            '/connect/static/src/icomoon/style.css',
            '/connect/static/src/services/audio_notification.js',
            '/connect/static/src/services/actions/*',
            '/connect/static/src/services/active_calls/*',
            '/connect/static/src/services/mail/*',
            '/connect/static/src/components/phone/*/*',
            '/connect/static/src/js/idb_error_handler.js',
            '/connect/static/src/js/main.js',
            '/connect/static/src/js/utils.js',
            '/connect/static/src/components/chat/*',
            '/connect/static/src/widgets/phone_field/*',
            '/connect/static/src/widgets/audio_recorder/*',
        ],
        # Dark mode overrides - loaded when Odoo enables dark mode
        'web.assets_web_dark': [
            '/connect/static/src/scss/phone.dark.scss',
            '/connect/static/src/components/chat/chat_thread.dark.scss',
        ],
    },
}
